
# Set None or 0 as no print. 1 as print out debug info.
DEBUG = 0
# Set the time as second.
CRON_JOB_TIME = 20
DEFAULT_LINE_INTERVAL = "1m"
DEFAULT_PRICE_INCREASE_RATE_THRESHOLD = 0.015
DEFAULT_VOLUME_INCREASE_RATE_THRESHOLD = -5
DEFAULT_DEPTH_DIFF = 0.4
DEFAULT_DEPTH_CHECK_TIMES = 3
# Set as second.
DEFAULT_DEPTH_CHECK_INTERVAL = 1
# this is second.
SCAN_EACH_SYMBOL_DELAY = 0
DEFAULT_THREAD = 5
QUOTA_VOLUME_THRESHOLD = 1000